// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhrqfmvnxpnhsciczeav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlocnFmbXZueHBuaHNjaWN6ZWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxODEzNDcsImV4cCI6MjA2OTc1NzM0N30.wFq07k3hRjdAhkSiriSovwNGiyCIYilvRCh8C__wMdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});